name: Release Tauri App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          
      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc
        
      - name: Install App Dependencies
        working-directory: ./apps/desktop-client
        run: |
          npm install --legacy-peer-deps --ignore-scripts
          npm install -D @tauri-apps/cli@^1.6.0
        
      - name: Build Tauri App
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectPath: ./apps/desktop-client
