name: Release Tauri App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v7
      
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          
      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc
        
      - name: Install App Dependencies
        working-directory: ./apps/desktop-client
        run: |
          npm install --legacy-peer-deps --ignore-scripts
          npm install -D @tauri-apps/cli@^1.6.0
        
      - name: Build Tauri App
        working-directory: ./apps/desktop-client
        run: npx tauri build
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: windows-installer
          path: target/release/bundle/msi/*.msi
